Parameters:
  EnvironmentName:
    Description: Deployment stage
    Type: String
  AdminOrgId:
    Description: ID of the admin organization
    Type: String
  LambdaCodeImageUri:
    Description: URI of the ECR image containing the lambda code
    Type: String

Conditions:
  IsProdEnvironment: !Equals [ !Ref EnvironmentName, "prod" ]

Resources:
  IngestionLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ImageUri: !Ref LambdaCodeImageUri
      Environment:
        Variables:
          ADMIN_ORG_ID: !Ref AdminOrgId
          ENVIRONMENT: !Ref EnvironmentName
      MemorySize: 3200 # 3GB
      Role: !GetAtt IngestionLambdaRole.Arn
      PackageType: Image
      Timeout: 900
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue
              'Fn::Sub': 'eks-vpc-dioptra-${EnvironmentName}'
        SubnetIds:
          - !ImportValue
              'Fn::Sub': 'ps-2-dioptra-${EnvironmentName}'

  IngestionLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: secrets-reader
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "secretsmanager:GetSecretValue"
                Resource: !If [IsProdEnvironment,
                  'arn:aws:secretsmanager:us-east-2:641017132295:secret:prod/postgres-credentials-iZUq4X',
                  'arn:aws:secretsmanager:us-east-2:641017132295:secret:dev/postgres-credentials-tPKCal'
                ]
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole'

  IngestionLambdaUrl:
    Type: AWS::Lambda::Url
    Properties: 
      AuthType: AWS_IAM
      TargetFunctionArn: !Ref IngestionLambda

Outputs:
  IngestionLambdaUrl:
    Description: URL of the ingestion lambda
    Value: !GetAtt IngestionLambdaUrl.FunctionUrl
    Export:
      Name: !Sub '${EnvironmentName}-ingestion-lambda-url'
  IngestionLambdaArn:
    Description: Arn of the ingestion lambda
    Value: !GetAtt IngestionLambda.Arn
    Export:
      Name: !Sub '${EnvironmentName}-ingestion-lambda-arn'
