# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  start-workflow:
    docker:
      - image: cimg/base:2021.10
    steps:
      - run:
          command: |
            echo "CIRCLE_BRANCH: ${CIRCLE_BRANCH}"

  build-and-push-image:
    executor:
      name: docker/machine
      dlc: true
    steps:
      - checkout
      - run:
          command: |
            git submodule init
            git submodule update --remote
      # aws-ecr/build-and-push-image doesn't use DLC as of circleci/aws-ecr@8.1.3 so we do it manually.
      - aws-ecr/ecr-login
      - docker/build:
          image: ingestion
          extra_build_args: '--compress'
          tag: <<pipeline.git.revision>>,latest,<<pipeline.git.tag>>
          registry: 641017132295.dkr.ecr.us-east-2.amazonaws.com
      - docker/push:
          image: ingestion
          tag: <<pipeline.git.revision>>,latest,<<pipeline.git.tag>>
          registry: 641017132295.dkr.ecr.us-east-2.amazonaws.com

  tag-image:
    docker:
      - image: cimg/aws:2022.11
    steps:
      - aws-ecr/tag-image:
          repo: ingestion
          source-tag: <<pipeline.git.revision>>
          target-tag: <<pipeline.git.tag>>

  cloudformation-deploy:
    parameters:
      stack-name:
        description: Name of the CloudFormation stack
        type: string
      stack-template:
        description: Path of the file containing the template
        type: string
      parameter-overrides:
        description: List of parameter values for the template param1=value1 param2=value2 ...
        type: string
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          command: |
            aws cloudformation deploy \
            --template << parameters.stack-template >> \
            --stack << parameters.stack-name >> \
            --parameter-overrides << parameters.parameter-overrides >> \
            --capabilities CAPABILITY_NAMED_IAM

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
  docker: circleci/docker@2.1.3
  aws-cli: circleci/aws-cli@2.0.3

workflows:
  'Build Branch':
    jobs:
      - start-workflow:
          filters:
            branches:
              ignore: /dev/
            tags:
              ignore: /.*/
      - build-and-push-image:
          requires:
            - start-workflow
          context:
            - aws-creds

  'Build and Deploy to Dev':
    jobs:
      - start-workflow:
          filters:
            branches:
              only:
                - dev
      - build-and-push-image:
          requires:
            - start-workflow
          context:
            - aws-creds
      - cloudformation-deploy:
          requires: 
            - build-and-push-image
          stack-name: ingestion-lambda-dev
          stack-template: ./cloudformation/ingestion-lambda.yaml
          parameter-overrides: "EnvironmentName=dev AdminOrgId=61723d86f1796f8b73854a2d LambdaCodeImageUri=641017132295.dkr.ecr.us-east-2.amazonaws.com/ingestion:<<pipeline.git.revision>>"
          context:
            - aws-creds

  'Release to Prod':
    jobs:
      - tag-image:
          context:
            - aws-creds
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - cloudformation-deploy:
          requires:
            - tag-image
          stack-name: ingestion-lambda-prod
          stack-template: ./cloudformation/ingestion-lambda.yaml
          parameter-overrides: "EnvironmentName=prod AdminOrgId=6180b101b62f12dd51d41238 LambdaCodeImageUri=641017132295.dkr.ecr.us-east-2.amazonaws.com/ingestion:<<pipeline.git.tag>>"
          context:
            - aws-creds
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
