# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  checkout-build-push-image:
    parameters:
      account-url:
        type: string
      aws-access-key-id:
        type: string
      aws-secret-access-key:
        type: string
      create-repo:
        type: boolean
      dockerfile:
        type: string
      path:
        type: string
      region:
        type: string
      repo:
        type: string
      tag:
        type: string
    executor:
      name: aws-ecr/default
      use-docker-layer-caching: true
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - aws-ecr/build-and-push-image:
          account-url: <<parameters.account-url>>
          aws-access-key-id: <<parameters.aws-access-key-id>>
          aws-secret-access-key: <<parameters.aws-secret-access-key>>
          create-repo: <<parameters.create-repo>>
          dockerfile: <<parameters.dockerfile>>
          path: <<parameters.path>>
          region: <<parameters.region>>
          repo: <<parameters.repo>>
          tag: <<parameters.tag>>

  helm-upgrade:
    parameters:
      cluster-name:
        type: string
      aws-region:
        type: string
        default: us-east-2
      helm-values:
        type: string
      image-tag:
        type: string
        default: <<pipeline.git.revision>>
    executor: aws-eks/python
    steps:
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: <<parameters.cluster-name>>
          aws-region: <<parameters.aws-region>>
      - checkout
      - helm/upgrade-helm-chart:
          atomic: true
          chart: ./helm
          helm-version: v3.6.0
          release-name: ingestion
          update-repositories: false
          values: <<parameters.helm-values>>
          values-to-override: imageTag=<<parameters.image-tag>>

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  helm: circleci/helm@1.2.0
  aws-eks: circleci/aws-eks@0.2

workflows:
  Integration:
    jobs:
      - checkout-build-push-image:
          name: build-image
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          path: .
          region: AWS_REGION
          repo: ingestion
          tag: <<pipeline.git.revision>>,latest,<<pipeline.git.tag>>
          context:
            - aws-creds
          filters:
            branches:
              only:
                - main
      - helm-upgrade:
          name: upgrade-dev
          cluster-name: dioptra-dev-eks
          helm-values: ./helm/values.dev.yaml
          image-tag: <<pipeline.git.revision>>
          context:
            - aws-creds
          requires:
            - build-image
          filters:
            branches:
              only:
                - main
  Delivery:
    jobs:
      - checkout-build-push-image:
          name: build-image
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          path: .
          region: AWS_REGION
          repo: ingestion
          tag: <<pipeline.git.revision>>,latest,<<pipeline.git.tag>>
          context:
            - aws-creds
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - helm-upgrade:
          name: upgrade-prod
          cluster-name: dioptra-prod-eks
          helm-values: ./helm/values.prod.yaml
          image-tag: <<pipeline.git.tag>>
          context:
            - aws-creds
          requires:
            - build-image
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
