environment: dev # TODO: remove this from the frontend deployment
replicas: 1
resources:
  requests:
    memory: "1Gi" # 32GB total
  limits:
    memory: "4Gi" # 32GB total

postgres:
  hostname: "dev-postresql-cluster.cluster-c58vxsd50oik.us-east-2.rds.amazonaws.com"
  user: postgres
  secret:
    name: "dioptra-postgres"
    key: "password"